<?php
/*
 Plugin Name: Change Admin Email Mothership
 Plugin URI: https://generalchicken.net/change-admin-email/
 Description: Restores functionality removed since WordPress 4.9. Allows the changing of the admin email by admins in single site without outbound email or recipient email credentials.
 Version: 3
 Author: John Dee
 Author URI: https://generalchicken.net/
*/

$ChangeAdminEmailMothership = new ChangeAdminEmailMothership;
$ChangeAdminEmailMothership->enableTestEmailRoute();

class ChangeAdminEmailMothership
{
    public function enableTestEmailRoute()
    {
        add_action('rest_api_init', array($this, 'doRegisterRoutes'));
    }

    public function doRegisterRoutes()
    {
        register_rest_route(
            'change-admin-email-plugin/v1',
            'test-email',
            array(
                'methods' => array('POST', 'GET'),
                'callback' => array(
                    new ChangeAdminEmailMothership(),
                    'testEmail',
                ),
                'permission_callback' => function () {
                    return true;
                }
            )
        );
    }

    public function testEmail(){
        $to = $_REQUEST['email'];
        $domain = $_REQUEST['domain'];
        $subject = "TEST INBOUND EMAIL";
        $message = "This is an autogenerated message from generalchicken.net. Someone requested this from $domain. This email confirms you're INBOUND email is working. If you did not request this message, it is safe to ignore.";
        wp_mail( $to, $subject, $message );
    }
}