actor: AcceptanceTester
modules:
   enabled:
      - \Helper\Acceptance
      - WebDriver:
         url: 'http://localhost:8888' # Site URL
         browser: chrome
         port: '4444'
         window_size: false
         clear_cookies: false
         restart: true
         keepCookies: true
         capabilities:
          chromeOptions:
            #args: ["--headless", "--disable-gpu"]
            #binary: "chrome"
            binary: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" # Path to Chrome binary
            #binary: "//Applications/MAMP/htdocs/wp-content/plugins/parler-wordpress-php/chromedriver"
            #java -Dwebdriver.chrome.driver=//Applications/MAMP/htdocs/wp-content/plugins/chromedriver77 -jar selenium.jar
            #java -Dwebdriver.chrome.driver=/var/www/chromedriver -jar selenium.jar